# Generated by Django 5.0.4 on 2024-04-19 03:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='custom word'),
        ),
        migrations.AlterModelOptions(
            name='dictionary',
            options={'verbose_name': '사용자 사전'},
        ),
        migrations.AddField(
            model_name='dictionary',
            name='creationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictionary',
            name='learned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
